### ISSUE TITLE
Warnings from dashboard.py in bokeh 0.11.1dev2

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#12]
```
hq-dhcp-20-83:~/datashader/examples> python dashboard.py
Starting server at http://localhost:5007/...
Loading Data...
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.axes.LinearAxis object at 0x112
865350>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.grids.Grid object at 0x11286519
0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.axes.LinearAxis object at 0x112
865f10>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.grids.Grid object at 0x112865c9
0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.renderers.TileRenderer object a
t 0x112865090>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.renderers.DynamicImageRenderer 
object at 0x112865510>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.axes.LinearAxis object at 0x112
865350>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.grids.Grid object at 0x11286519
0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.axes.LinearAxis object at 0x112
865f10>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.grids.Grid object at 0x112865c9
0>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.renderers.TileRenderer object a
t 0x112865090>, which is a client-only or invalid attribute that shouldn't have been sent
WARNING:bokeh.core.properties:JSON had attr u'parent' on obj <bokeh.models.renderers.DynamicImageRenderer 
object at 0x112865510>, which is a client-only or invalid attribute that shouldn't have been sent
```

**Comment by bryevdv** [comment]
This is related to a recent change in Bokeh, there was a line that should have been removed that was not. Can you make an issue there?

**Comment by jbednar** [comment]
Sure, though I don't know how to reproduce it without Datashader...

**Comment by bryevdv** [comment]
just link to this

**Comment by jbednar** [comment]
I'm now getting a different set of warnings, from the same running copy of dashboard.py, after zooming and panning some more:

```
ERROR:tornado.application:Uncaught exception GET /datashader?height=560&width=890&select=-8247848.40052651
9,4969192.967949045,-8224650.297361891,4983789.527243633 (::1)
HTTPServerRequest(protocol='http', host='localhost:5007', method='GET', uri='/datashader?height=560&width=
890&select=-8247848.400526519,4969192.967949045,-8224650.297361891,4983789.527243633', version='HTTP/1.1',
 remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch',
'Host': 'localhost:5007', 'Accept': 'image/webp,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh;
 Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Conn
ection': 'keep-alive', 'Referer': 'http://localhost:5007/'})
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "//anaconda/lib/python2.7/site-packages/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "dashboard.py", line 46, in get
    pix = tf.interpolate(agg.agg_field, (255, 204, 204), 'red', how=self.model.transfer_function)
  File "/Users/jbednar/datashader/datashader/transfer_functions.py", line 92, in interpolate
    span = [data[~missing].min(), data[~missing].max()]
UnboundLocalError: local variable 'missing' referenced before assignment
ERROR:tornado.access:500 GET /datashader?height=560&width=890&select=-8247848.400526519,4969192.967949045,
-8224650.297361891,4983789.527243633 (::1) 2746.93ms
ERROR:tornado.application:Uncaught exception GET /datashader?height=560&width=890&select=-8247848.40052652
,4969192.967949045,-8224650.297361892,4983789.527243633 (::1)
HTTPServerRequest(protocol='http', host='localhost:5007', method='GET', uri='/datashader?height=560&width=
890&select=-8247848.40052652,4969192.967949045,-8224650.297361892,4983789.527243633', version='HTTP/1.1',
remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', '
Host': 'localhost:5007', 'Accept': 'image/webp,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh;
Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Conne
ction': 'keep-alive', 'Referer': 'http://localhost:5007/'})
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "//anaconda/lib/python2.7/site-packages/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "dashboard.py", line 46, in get
    pix = tf.interpolate(agg.agg_field, (255, 204, 204), 'red', how=self.model.transfer_function)
  File "/Users/jbednar/datashader/datashader/transfer_functions.py", line 92, in interpolate
    span = [data[~missing].min(), data[~missing].max()]
```

**Comment by jcrist** [comment]
That's a bug in the transfer function code. Should be fixed shortly.

**Comment by jcrist** [comment]
The bokeh warnings appear to be fixed, and the transfer function warnings were fixed a while ago. Closing.

**Comment by cweinschenk** [comment]
I see that this post was closed about a month ago but I am getting a similar warning using Bokeh 0.11.1-py35_0

WARNING:bokeh.core.properties:JSON had attr 'silent' on obj <bokeh.models.ranges.Range1d object at 0x10afa77b8>, which is a client-only or invalid attribute that shouldn't have been sent

I am using a bokeh server to update glyphs on a GMap with drop down box. The glyphs aren't updating and I am not sure if it related to this warning or something else. Figured I should inquire.
