### ISSUE TITLE
Error while importing datashader

### ISSUE THREAD

**Issue by jbednar** [bokeh/datashader#158]
From: http://stackoverflow.com/questions/37431925/error-while-importing-datashader

Code: 

```python
import datashader as ds
```

Error: 

```python
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Traceback (most recent call last):

```python
File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\llvmlite\binding\ffi.py", line 40, in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\datashader\__init__.py", line 5, in <module>
    from .core import Canvas
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\datashader\core.py", line 8, in <module>
    from .utils import Dispatcher, ngjit
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\datashader\utils.py", line 5, in <module>
    import numba as nb
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\numba\__init__.py", line 9, in <module>
    from . import runtests, decorators
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\numba\decorators.py", line 8, in <module>
    from . import config, sigutils
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\numba\config.py", line 10, in <module>
    import llvmlite.binding as ll
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\llvmlite\binding\__init__.py", line 6, in <module>
    from .dylib import *
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\llvmlite\binding\dylib.py", line 4, in <module>
    from . import ffi
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\llvmlite\binding\ffi.py", line 45, in <module>
    lib = ctypes.CDLL(_lib_name)
  File "D:\Adarsh\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by jcrist** [comment]
This looks like an issue with their install of llvm/llvmlite, not an issue with datashader. Closing.
