### ISSUE TITLE
Error with sample data download?

### ISSUE THREAD

**Issue by miktoki** [bokeh/datashader#194]
I tried updating datashader(python3.4) using conda to 0.3. When attempting to run  `datashader-download-data`  I get the following error:

    Traceback (most recent call last):
      File "/home/mikaelt/_software/miniconda/bin/datashader-download-data", line 9, in <module>
        load_entry_point('datashader==0.3.0', 'console_scripts', 'datashader-download-data')()
      File "/home/mikaelt/_software/miniconda/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/mikaelt/_software/miniconda/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/home/mikaelt/_software/miniconda/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/home/mikaelt/_software/miniconda/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'examples'

When attempting to do the same using a python2.7 environment:

    Traceback (most recent call last):
      File "/home/mikaelt/_software/miniconda/envs/py27/bin/datashader-download-data", line 9, in <module>
        load_entry_point('datashader==0.3.0', 'console_scripts', 'datashader-download-data')()
      File "/home/mikaelt/_software/miniconda/envs/py27/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
      File "/home/mikaelt/_software/miniconda/envs/py27/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
      File "/home/mikaelt/_software/miniconda/envs/py27/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
      File "/home/mikaelt/_software/miniconda/envs/py27/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
    ImportError: No module named examples.download_sample_data

It seems like I am having difficulties downloading the data due to being unable to find the path to the module `examples`.

**Comment by miktoki** [comment]
Running `download_sample_data-py` works as expected

**Comment by jbednar** [comment]
I've now made examples into a module; before it was just a directory.  I'm about to make a new datashader release, and hopefully it will work now.

**Comment by jbednar** [comment]
Closing due to lack of input; hopefully it worked well in the new release!

**Comment by assismauro** [comment]
I just installed it and I´m getting the same error:

C:\Anaconda\pkgs\datashader-0.3.2-py27_0\Scripts>python datashader-download-data-script.py
Traceback (most recent call last):
  File "datashader-download-data-script.py", line 9, in <module>
    load_entry_point('datashader==0.3.2', 'console_scripts', 'datashader-download-data')()
  File "C:\Anaconda\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resources\__init__.py", line 547, in load_entry_point
  File "C:\Anaconda\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resources\__init__.py", line 2720, in load_entry_point
  File "C:\Anaconda\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resources\__init__.py", line 2380, in load
  File "C:\Anaconda\lib\site-packages\setuptools-20.1.1-py2.7.egg\pkg_resources\__init__.py", line 2386, in resolve
ImportError: No module named examples.download_sample_data

**Comment by jbednar** [comment]
Thanks for the update!  I don't think I'll have time to look into it today, but hopefully early next week!  Meanwhile, it should work if you run the download_sample_data.py script in examples/ manually...

**Comment by assismauro** [comment]
I was installed datashader using conda, and there´s no samples dir there.

Now I cloned/installed it from git, and ran it as you said above and it´s downloading now.

Tks!

**Comment by jbednar** [comment]
Makes sense, thanks!  Need to fix how the conda package is built, then.

**Comment by jbednar** [comment]
See https://github.com/bokeh/datashader/blob/master/README.md for instructions for how to download the examples, using the latest conda packages built today.
