### ISSUE TITLE
concatenating dataframes - incompatible categories in categorical concat

### ISSUE THREAD

**Issue by smsaladi** [bokeh/datashader#241]
I am running into an error that occurs from concatenating dataframes using `dd.concat`. However, it does not occur when I concatenate using `pd.concat`. Is there something that I should be doing for this to work correctly?

concatenate pandas dataframes of csv files into a single dataframe:
```python
sim_df = pd.concat(all_dfs, axis=0)
sim_df_dd = dd.concat(all_dfs, axis=0, interleave_partitions=True)

sim_df['idx_fn'] = sim_df['idx_fn'].astype("category")
sim_df_dd['idx_fn'] = sim_df_dd['idx_fn'].astype("category")

sim_df_pd_to_dd = dd.from_pandas(sim_df, npartitions=100)
```

```python
# confirm that column is categorical
sim_df['idx_fn'].dtype, sim_df_dd['idx_fn'].dtype, sim_df_pd_to_dd['idx_fn'].dtype
(category, category, category)
```

```
# set up plot
plot_width = 1000
plot_height = int(plot_width*0.5)
canvas = ds.Canvas(plot_width=plot_width, plot_height=plot_height,
                   x_range = (0, 102062848), y_range = (0, 700))
```

Works:
```python
agg = canvas.line(sim_df, 'TS', 'BOND', agg=ds.reductions.count_cat('idx_fn'))
```

Works:
```python
agg = canvas.line(sim_df_pd_to_dd, 'TS', 'BOND', agg=ds.reductions.count_cat('idx_fn'))
```

Doesn't work:
```python
agg = canvas.line(sim_df_dd, 'TS', 'BOND', agg=ds.reductions.count_cat('idx_fn'))
```

```text
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-8cadaecb527f> in <module>()
      4 canvas = ds.Canvas(plot_width=plot_width, plot_height=plot_height,
      5                    x_range = (0, 102062848), y_range = (0, 700))
----> 6 agg = canvas.line(sim_df_dd, 'TS', 'BOND', agg=ds.reductions.count_cat('idx_fn'))

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/datashader/core.py in line(self, source, x, y, agg)
    167         if agg is None:
    168             agg = any()
--> 169         return bypixel(source, self, Line(x, y), agg)
    170 
    171     def raster(self,

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/datashader/core.py in bypixel(source, canvas, glyph, agg)
    316     glyph.validate(schema)
    317     agg.validate(schema)
--> 318     return bypixel.pipeline(source, schema, canvas, glyph, agg)
    319 
    320 

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/datashader/utils.py in __call__(self, head, *rest, **kwargs)
     40         typ = type(head)
     41         if typ in lk:
---> 42             return lk[typ](head, *rest, **kwargs)
     43         for cls in getmro(typ)[1:]:
     44             if cls in lk:

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/datashader/dask.py in dask_pipeline(df, schema, canvas, glyph, summary)
     23     dsk = df._optimize(dsk, name)
     24 
---> 25     return get(dsk, name)
     26 
     27 

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     56     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     57                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 58                         **kwargs)
     59 
     60     return results

/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                     _execute_task(task, data)  # Re-execute locally
    480                 else:
--> 481                     raise(remote_exception(res, tb))
    482             state['cache'][key] = res
    483             finish_task(dsk, key, state, results, keyorder.get)

ValueError: incompatible categories in categorical concat

Traceback
---------
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/datashader/dask.py", line 90, in chunk
    df = pd.concat([df.iloc[-1:], df2])
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/tools/merge.py", line 846, in concat
    return op.get_result()
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/tools/merge.py", line 1038, in get_result
    copy=self.copy)
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/core/internals.py", line 4545, in concatenate_block_managers
    for placement, join_units in concat_plan]
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/core/internals.py", line 4545, in <listcomp>
    for placement, join_units in concat_plan]
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/core/internals.py", line 4650, in concatenate_join_units
    concat_values = _concat._concat_compat(to_concat, axis=concat_axis)
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/types/concat.py", line 127, in _concat_compat
    return _concat_categorical(to_concat, axis=axis)
  File "/ul/saladi/anaconda3/envs/mdtraj_py3/lib/python3.5/site-packages/pandas/types/concat.py", line 187, in _concat_categorical
    raise ValueError("incompatible categories in categorical concat")
```

**Comment by jbednar** [comment]
That sounds like an issue to raise with dask, as it doesn't *seem* to be related to code in datashader.  But you'll want to have a data file that you can post to reproduce the issue, preferably something small and clear, or else they probably won't be able to address it.
