### ISSUE TITLE
Package fails to load after installing via anaconda

### ISSUE THREAD

**Issue by bjfar** [bokeh/datashader#363]
I am in a Scientific Linux environment on a high-performance cluster, and trying to get datashader to load up. I installed anaconda by following the instructions for python 2.7 here:      https://docs.continuum.io/anaconda/install-linux.html
This seems to have gone fine. I then created a new environment via:
`    conda create --name plotting datashader bokeh`
which seemed to download and install a bunch of things. So I then went into this environment, loaded python, and tried to import datashader:
```
    source activate plotting
    python
    import datashader
```
But it fails with the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/odo/__init__.py", line 11, in <module>
    from .utils import ignoring
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/odo/utils.py", line 18, in <module>
    from datashape.discovery import is_zero_time
ImportError: cannot import name is_zero_time
```
Just for a test, I went into this utils.py file and hacked out the calls to this function, and tried again. The traceback then becomes:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/odo/__init__.py", line 12, in <module>
    from .convert import convert
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/odo/convert.py", line 11, in <module>
    from .chunks import chunks, Chunks
  File "/net/people/plgfarmer/anaconda2/envs/plotting/lib/python2.7/site-packages/odo/chunks.py", line 5, in <module>
    from toolz import memoize, first, peek
ImportError: cannot import name peek
```
I guess probably these versions of odo and maybe datashape are not correct, but then that seems to suggest that there is something wrong with the datashader installer in conda? Or have I done something wrong in the install procedure? But datashader seems to be installed, it just fails to load due to these dependency problems. It could be due to other junk that is installed on the cluster I guess, however I thought the whole point of anaconda was to solve these kind of issues. And on top of that, the tracebacks seem to indicate that the anaconda-installed versions of these packages are indeed the ones it is trying to use. So I am out of ideas.

**Comment by jbednar** [comment]
Ack! Yes, conda is supposed to avoid issues like that, so it is possible that we have not properly specified which versions of odo, datashape, or toolz we need.  You are probably not getting the most recent version of datashader, as I don't think it's been updated on the main channel since our recent release, which is only on the `bokeh` channel right now.  Can you please try ``conda install odo datashape toolz`` and list the output here (to show the installed and most current versions of those libraries) and then ``conda install -c bokeh datashader bokeh`` to make sure you are using the current datashader version?

**Comment by bjfar** [comment]
Sure thing. But actually let me start from the beginning and paste all the output. So I removed the new environment and re-created it:

```
> conda create --name plotting datashader bokeh
Fetching package metadata .........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::bokeh-0.12.5-py27_1, defaults::datashader-0.3.0-py27_0
  - defaults::bokeh-0.12.4-py27_0, defaults::datashader-0.4.0-py27_0

Package plan for installation in environment /net/people/plgfarmer/anaconda2/envs/plotting:

The following NEW packages will be INSTALLED:

    backports:          1.0-py27_0        
    backports_abc:      0.5-py27_0        
    bokeh:              0.12.5-py27_1     
    cloudpickle:        0.2.2-py27_0      
    dask:               0.14.3-py27_1     
    datashader:         0.3.0-py27_0      
    datashape:          0.5.4-py27_0      
    decorator:          4.0.11-py27_0     
    enum34:             1.1.6-py27_0      
    freetype:           2.5.5-2           
    funcsigs:           1.0.2-py27_0      
    futures:            3.1.1-py27_0      
    jbig:               2.1-0             
    jinja2:             2.9.6-py27_0      
    jpeg:               9b-0              
    libpng:             1.6.27-0          
    libtiff:            4.0.6-3           
    llvmlite:           0.18.0-py27_0     
    locket:             0.2.0-py27_1      
    markupsafe:         0.23-py27_2       
    mkl:                2017.0.1-0        
    multipledispatch:   0.4.9-py27_0      
    networkx:           1.11-py27_0       
    numba:              0.33.0-np112py27_0
    numpy:              1.12.1-py27_0     
    odo:                0.5.0-py27_1      
    olefile:            0.44-py27_0       
    openssl:            1.0.2l-0          
    pandas:             0.20.1-np112py27_0
    partd:              0.3.8-py27_0      
    pillow:             4.1.1-py27_0      
    pip:                9.0.1-py27_1      
    python:             2.7.13-0          
    python-dateutil:    2.6.0-py27_0      
    pytz:               2017.2-py27_0     
    pyyaml:             3.12-py27_0       
    readline:           6.2-2             
    requests:           2.14.2-py27_0     
    setuptools:         27.2.0-py27_0     
    singledispatch:     3.4.0.3-py27_0    
    six:                1.10.0-py27_0     
    sqlite:             3.13.0-0          
    ssl_match_hostname: 3.4.0.2-py27_1    
    tk:                 8.5.18-0          
    toolz:              0.8.2-py27_0      
    tornado:            4.5.1-py27_0      
    wheel:              0.29.0-py27_0     
    xarray:             0.9.5-py27_0      
    xz:                 5.2.2-1           
    yaml:               0.1.6-0           
    zlib:               1.2.8-3           

Proceed ([y]/n)? y
```

Then we are in the situation described in the issue. Now for your requested output:

```
> source activate plotting
> conda install odo datashape toolz
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /net/people/plgfarmer/anaconda2/envs/plotting:
#
datashape                 0.5.4                    py27_0  
odo                       0.5.0                    py27_1  
toolz                     0.8.2                    py27_0 
```
 and

```
> conda install -c bokeh datashader bokeh
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /net/people/plgfarmer/anaconda2/envs/plotting:

The following NEW packages will be INSTALLED:

    colorcet:       0.9.1-py27_0  bokeh
    futures-compat: 1.0-py2_0          

The following packages will be UPDATED:

    datashader:     0.3.0-py27_0        --> 0.5.0-py27_0  bokeh

The following packages will be SUPERSEDED by a higher-priority channel:

    bokeh:          0.12.5-py27_1       --> 0.12.5-py27_0 bokeh

Proceed ([y]/n)? y
```

I still get the same errors with "import datashader" after this change.

**Comment by jbednar** [comment]
Hmm; that's odd.  I've got precisely the versions you do with no problems, on Mac OS X.  And the most recent [Debian Linux build](https://travis-ci.org/bokeh/datashader/jobs/235735437) seems fine as well.  What version of Scientific LInux are you on?

**Comment by bjfar** [comment]
Ahh sorry I remembered wrong, this particular cluster is not Scientific Linux, it is apparently Linux CentOS 7. Some extra version info below: 

```
> lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

> cat /proc/version
Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
```

**Comment by bjfar** [comment]
Ok I made some progress. It seems like python is not in fact using the datashape version that is installed by conda:

```
(plotting) $ conda install datashape=0.5.4
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /net/people/plgfarmer/anaconda2/envs/plotting:
#
datashape                 0.5.4                    py27_0  
(plotting) $ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import datashape
>>> datashape.__version__
'0.4.6'
>>> print datashape.__file__
/net/software/local/python/2.7.9/lib/python2.7/site-packages/datashape/__init__.pyc
```

I don't know anaconda very well so I have no idea why it would be misbehaving like this.

**Comment by bjfar** [comment]
Ok I figured it out. Anaconda is just easily broken by environment variables, it seems: [](https://conda.io/docs/troubleshooting.html#conda-claims-installed)

In particular, since I am on a cluster, it sets all kinds of stuff as part of its own user-environment management, including PYTHONPATH, which apparantly screws up anaconda. So the solution is to unset this environment variable:
 
`unset PYTHONPATH`

and then anaconda can pick up the correct versions of everything, and datashader successfully imports.

**Comment by jbednar** [comment]
Aha!  It was all sounding very fishy, and that explains it! Glad you got it working.
