### ISSUE TITLE
import datashader occurs exception:"AttributeError: 'CastInstr' object has no attribute 'addrspace'"

### ISSUE THREAD

**Issue by huhai463127310** [bokeh/datashader#391]
when I execute "import datashader", it occurs an exception like this:

```
(ds) bigdata@iZuf6istfz0zvzaadgdwhhZ:~/download$ python -c "from datashader import examples ; examples('datashader-examples')"
/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/__init__.py", line 65, in <module>
    from .backends.dask import dask
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/dask.py", line 13, in <module>
    import dask.dataframe as dd
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 9, in <module>
    from .optimize import optimize
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/optimize.py", line 10, in <module>
    import fastparquet  # noqa: F401
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/__init__.py", line 15, in <module>
    from .core import read_thrift
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/core.py", line 10, in <module>
    from . import encoding
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/encoding.py", line 57, in <module>
    @numba.jit(nogil=True)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/decorators.py", line 173, in wrapper
    **dispatcher_args)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/dispatcher.py", line 467, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/base.py", line 246, in __init__
    self.init()
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/cpu.py", line 48, in init
    rtsys.initialize(self)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrt.py", line 35, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 199, in compile_nrt_functions
    ir_mod, library = create_nrt_module(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 185, in create_nrt_module
    _define_nrt_meminfo_data(ir_mod)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 40, in _define_nrt_meminfo_data
    data_ptr = builder.load(cgutils.gep(builder, struct_ptr, 0, 3))
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/cgutils.py", line 819, in gep
    return builder.gep(ptr, idx, name=name, inbounds=inbounds)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/builder.py", line 769, in gep
    inbounds=inbounds, name=name)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/instructions.py", line 456, in __init__
    typ = typ.as_pointer(ptr.addrspace)
AttributeError: 'CastInstr' object has no attribute 'addrspace'
(ds) bigdata@iZuf6istfz0zvzaadgdwhhZ:~/download$ 
(ds) bigdata@iZuf6istfz0zvzaadgdwhhZ:~/download$ python -c "import datashader"
/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/__init__.py", line 65, in <module>
    from .backends.dask import dask
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/dask.py", line 13, in <module>
    import dask.dataframe as dd
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 9, in <module>
    from .optimize import optimize
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/optimize.py", line 10, in <module>
    import fastparquet  # noqa: F401
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/__init__.py", line 15, in <module>
    from .core import read_thrift
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/core.py", line 10, in <module>
    from . import encoding
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/encoding.py", line 57, in <module>
    @numba.jit(nogil=True)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/decorators.py", line 173, in wrapper
    **dispatcher_args)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/dispatcher.py", line 467, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/base.py", line 246, in __init__
    self.init()
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/cpu.py", line 48, in init
    rtsys.initialize(self)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrt.py", line 35, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 199, in compile_nrt_functions
    ir_mod, library = create_nrt_module(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 185, in create_nrt_module
    _define_nrt_meminfo_data(ir_mod)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 40, in _define_nrt_meminfo_data
    data_ptr = builder.load(cgutils.gep(builder, struct_ptr, 0, 3))
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/cgutils.py", line 819, in gep
    return builder.gep(ptr, idx, name=name, inbounds=inbounds)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/builder.py", line 769, in gep
    inbounds=inbounds, name=name)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/instructions.py", line 456, in __init__
    typ = typ.as_pointer(ptr.addrspace)
AttributeError: 'CastInstr' object has no attribute 'addrspace'
(ds) bigdata@iZuf6istfz0zvzaadgdwhhZ:~/download$ 
(ds) bigdata@iZuf6istfz0zvzaadgdwhhZ:~/download$ python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datashader
/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/__init__.py", line 5, in <module>
    from .core import Canvas
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/datashader/core.py", line 5, in <module>
    from odo import discover
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/__init__.py", line 65, in <module>
    from .backends.dask import dask
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/odo/backends/dask.py", line 13, in <module>
    import dask.dataframe as dd
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 9, in <module>
    from .optimize import optimize
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/dask/dataframe/optimize.py", line 10, in <module>
    import fastparquet  # noqa: F401
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/__init__.py", line 15, in <module>
    from .core import read_thrift
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/core.py", line 10, in <module>
    from . import encoding
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/fastparquet/encoding.py", line 57, in <module>
    @numba.jit(nogil=True)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/decorators.py", line 173, in wrapper
    **dispatcher_args)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/dispatcher.py", line 467, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/base.py", line 246, in __init__
    self.init()
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/targets/cpu.py", line 48, in init
    rtsys.initialize(self)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrt.py", line 35, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 199, in compile_nrt_functions
    ir_mod, library = create_nrt_module(ctx)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 185, in create_nrt_module
    _define_nrt_meminfo_data(ir_mod)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/runtime/nrtdynmod.py", line 40, in _define_nrt_meminfo_data
    data_ptr = builder.load(cgutils.gep(builder, struct_ptr, 0, 3))
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/numba/cgutils.py", line 819, in gep
    return builder.gep(ptr, idx, name=name, inbounds=inbounds)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/builder.py", line 769, in gep
    inbounds=inbounds, name=name)
  File "/home/bigdata/bin/anaconda2/envs/ds/lib/python3.6/site-packages/llvmlite/ir/instructions.py", line 456, in __init__
    typ = typ.as_pointer(ptr.addrspace)
AttributeError: 'CastInstr' object has no attribute 'addrspace'
```

- installation method
> The best way to get started with Datashader is install it together with our extensive set of examples, following the instructions in the examples [README](https://raw.githubusercontent.com/bokeh/datashader/master/examples/README.md).

- os version
```
Linux iZuf6istfz0zvzaadgdwhhZ 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- conda list
```
# packages in environment at /home/bigdata/bin/anaconda2/envs/ds:
#
affine                    2.0.0.post1              py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
biggus                    0.15.0                   py36_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     0.12.7dev3                 py_0    bokeh/label/dev
boto3                     1.4.4                    py36_0    conda-forge
botocore                  1.5.55                   py36_0    conda-forge
bottleneck                1.2.0               np112py36_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
cachey                    0.1.1                     <pip>
cartopy                   0.15.1              np112py36_2    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cf_units                  1.1.3                    py36_1    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.3.1                    py36_0    conda-forge
colorcet                  0.9.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cryptography              1.9                      py36_0    conda-forge
curl                      7.52.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.25.2                   py36_1    conda-forge
dask                      0.15.0                   py36_0    conda-forge
datashader                0.6.0dev2                py36_0    bokeh/label/dev
datashape                 0.5.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dbus                      1.10.10                       3    conda-forge
decorator                 4.0.11                   py36_0    conda-forge
dill                      0.2.6                    py36_0    conda-forge
distributed               1.17.1                   py36_0    conda-forge
docutils                  0.13.1                   py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.1.0                         2    conda-forge
fastparquet               0.1.0                    py36_2    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         1    conda-forge
futures-compat            1.0                       py3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
gdal                      2.2.0               np112py36_3    conda-forge
geos                      3.5.1                         1    conda-forge
geoviews                  1.2.0                    py36_0    ioam
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5netcdf                  0.3.1                    py36_0    conda-forge
h5py                      2.7.0               np112py36_1    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
holoviews                 1.7.0                    py36_0    conda-forge
html5lib                  0.999                    py36_0    conda-forge
hypothesis                3.11.6                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py36_0    conda-forge
imageio                   2.2.0                    py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
iris                      1.13.0                   py36_1    conda-forge
jedi                      0.10.0                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
jmespath                  0.9.2                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.0.1                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
jupyter_dashboards        0.7.0                    py36_0    conda-forge
kealib                    1.4.7                         2    conda-forge
krb5                      1.14.2                        0    conda-forge
lancet                    0.9.0                    py36_0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.0                         0    conda-forge
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libiconv                  1.14                          4    conda-forge
libmo_unpack              3.0                           1    conda-forge
libnetcdf                 4.4.1.1                       5    conda-forge
libpng                    1.6.28                        0    conda-forge
libpq                     9.5.4                         4    conda-forge
libsodium                 1.0.10                        0    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
libxslt                   1.1.29                        4    conda-forge
llvmlite                  0.19.0.dev              py36_18    numba
locket                    0.2.0                    py36_1    conda-forge
lxml                      3.8.0                    py36_0    conda-forge
lzo                       2.06                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
markupsafe                1.0                      py36_0    conda-forge
marshmallow               2.13.5                    <pip>
matplotlib                2.0.2               np112py36_0    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mo_pack                   0.2.0               np112py36_0    conda-forge
msgpack-python            0.4.8                    py36_0    conda-forge
multipledispatch          0.4.9                    py36_0    conda-forge
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
nc_time_axis              1.0.2                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.2.9               np112py36_0    conda-forge
networkx                  1.11                     py36_0    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numba                     0.34.0.dev        np112py36_413    numba
numexpr                   2.6.2               np112py36_0    conda-forge
numpy                     1.12.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
odo                       0.5.0                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
olefile                   0.44                     py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2k                        0    conda-forge
owslib                    0.14.0                   py36_0    conda-forge
pandas                    0.20.2              np112py36_1    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
param                     1.5.1                    py36_0    conda-forge
paramnb                   2.0.2                    py36_0    ioam
partd                     0.3.8                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pillow                    4.1.1                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
ply                       3.9                      py36_0    conda-forge
proj4                     4.9.3                         4    conda-forge
prompt_toolkit            1.0.14                   py36_0    conda-forge
psutil                    5.2.1                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.4.34                   py36_0    conda-forge
pycparser                 2.17                     py36_0    conda-forge
pyepsg                    0.3.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyke                      1.1.1                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pyshp                     1.2.11                   py36_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytables                  3.4.2               np112py36_1    conda-forge
pytest                    3.1.2                    py36_0    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
python-snappy             0.5.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pywavelets                0.5.2               np112py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         3    conda-forge
qtconsole                 4.3.0                    py36_0    conda-forge
rasterio                  1.0a9               np112py36_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.1                   py36_0    conda-forge
s3transfer                0.1.10                   py36_1    conda-forge
scikit-image              0.13.0              np112py36_0    conda-forge
scipy                     0.19.1          np112py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                33.1.1                   py36_0    conda-forge
shapely                   1.5.17              np112py36_3    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
snappy                    1.1.4                         1    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sortedcontainers          1.5.3                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.8.0               np112py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3                      py36_0    conda-forge
thriftpy                  0.3.9                    py36_0    conda-forge
tk                        8.5.19                        1    conda-forge
toolz                     0.8.2                    py36_0    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
udunits2                  2.2.23                        0    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
util-linux                2.21                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wcwidth                   0.1.7                    py36_0    conda-forge
webargs                   1.7.0                     <pip>
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
xarray                    0.9.6                    py36_0    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zict                      0.1.2                    py36_0    conda-forge
zlib                      1.2.11                        0    conda-forge
zope                      1.0                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zope.interface            4.4.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
```

**Comment by adnan-wahab** [comment]
I'm getting the same issue

**Comment by jbednar** [comment]
Hmm; could be a problem with numba and the latest llvmlite.  Can you try pinning llvmlite=0.18.0?

**Comment by adnan-wahab** [comment]
i conda installed llvmlite and recreated the environment and that fixed it

**Comment by jbednar** [comment]
Great!  I've updated examples/environment.yml to pull numba and llvmlite from the main channel instead of the numba channel, now that numba=0.33 is available on main, and I think this should fix the issue.

**Comment by huhai463127310** [comment]
It works after updated examples/environment.yml.   

But import datashader 0.5.0 will occur segment falut when it work with scipy-0.18.1 on python 2.7.13.
